#!/bin/sh
# This is a generated file; do not edit or check into version control.
export "FLUTTER_ROOT=/Volumes/Macos-Ext/Users/larpoux/flutter"
export "FLUTTER_APPLICATION_PATH=/Volumes/Macos-Ext/Users/larpoux/projmac/flutter_sound/flutter_sound_web"
export "FLUTTER_TARGET=lib/main.dart"
export "FLUTTER_BUILD_DIR=build"
export "SYMROOT=${SOURCE_ROOT}/../build/ios"
export "OTHER_LDFLAGS=$(inherited) -framework Flutter"
export "FLUTTER_FRAMEWORK_DIR=/Volumes/Macos-Ext/Users/larpoux/flutter/bin/cache/artifacts/engine/ios"
export "FLUTTER_BUILD_NAME=6.4.3"
export "FLUTTER_BUILD_NUMBER=44"
export "DART_OBFUSCATION=false"
export "TRACK_WIDGET_CREATION=false"
export "TREE_SHAKE_ICONS=false"
export "PACKAGE_CONFIG=.packages"
